{-# OPTIONS_GHC -Wno-unused-imports #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE TypeFamilies #-}
module Capnp.Capnp.Cxx where

-- Code generated by capnpc-haskell. DO NOT EDIT.
-- Generated from schema file: capnp/c++.capnp

import Data.Int
import Data.Word
import qualified Data.Bits
import qualified Data.Maybe
import qualified Codec.Capnp
import qualified Data.Capnp.Basics
import qualified Data.Capnp.Basics.Generic
import qualified Data.Capnp.TraversalLimit
import qualified Data.Capnp.Untyped
import qualified Data.Capnp.Message.Mutable



