{-# OPTIONS_GHC -Wno-unused-imports #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MultiParamTypeClasses #-}
module Data.Capnp.ById.Xb8630836983feed7 where

-- Code generated by capnpc-haskell. DO NOT EDIT.
-- Generated from schema file: /usr/include/capnp/persistent.capnp

import Data.Int
import Data.Word
import qualified Data.Bits

import qualified Codec.Capnp
import qualified Data.Capnp.BuiltinTypes
import qualified Data.Capnp.TraversalLimit
import qualified Data.Capnp.Untyped

import qualified Data.Capnp.ById.Xbdf87d7bb8304e81

newtype Persistent'SaveResults b = Persistent'SaveResults (Data.Capnp.Untyped.Struct b)

get_Persistent'SaveResults'sturdyRef :: Data.Capnp.Untyped.ReadCtx m b => Persistent'SaveResults b -> m (Maybe (Data.Capnp.Untyped.Ptr b))
get_Persistent'SaveResults'sturdyRef (Persistent'SaveResults struct) =
    Data.Capnp.Untyped.getPtr 0 struct
    >>= Codec.Capnp.fromPtr (Data.Capnp.Untyped.message struct)

instance Codec.Capnp.IsPtr (Persistent'SaveResults b) b where
    fromPtr msg ptr = fmap Persistent'SaveResults (Codec.Capnp.fromPtr msg ptr)

newtype Persistent'SaveParams b = Persistent'SaveParams (Data.Capnp.Untyped.Struct b)

get_Persistent'SaveParams'sealFor :: Data.Capnp.Untyped.ReadCtx m b => Persistent'SaveParams b -> m (Maybe (Data.Capnp.Untyped.Ptr b))
get_Persistent'SaveParams'sealFor (Persistent'SaveParams struct) =
    Data.Capnp.Untyped.getPtr 0 struct
    >>= Codec.Capnp.fromPtr (Data.Capnp.Untyped.message struct)

instance Codec.Capnp.IsPtr (Persistent'SaveParams b) b where
    fromPtr msg ptr = fmap Persistent'SaveParams (Codec.Capnp.fromPtr msg ptr)
