{-# OPTIONS_GHC -Wno-unused-imports #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE TypeFamilies #-}
module Capnp.ById.X8ef99297a43a5e34 where

-- Code generated by capnpc-haskell. DO NOT EDIT.
-- Generated from schema file: capnp/json.capnp

import Data.Int
import Data.Word
import qualified Data.Bits
import qualified Data.Maybe
import qualified Codec.Capnp
import qualified Data.Capnp.BuiltinTypes
import qualified Data.Capnp.BuiltinTypes.Generic
import qualified Data.Capnp.TraversalLimit
import qualified Data.Capnp.Untyped
import qualified Data.Capnp.Message.Mutable

import qualified Capnp.ById.Xbdf87d7bb8304e81

data JsonValue msg
    = JsonValue'null
    | JsonValue'boolean Bool
    | JsonValue'number Double
    | JsonValue'string Data.Capnp.BuiltinTypes.Text
    | JsonValue'array (Data.Capnp.Untyped.ListOf (JsonValue msg))
    | JsonValue'object (Data.Capnp.Untyped.ListOf (JsonValue'Field msg))
    | JsonValue'call (JsonValue'Call msg)
    | JsonValue'unknown' Word16








instance Codec.Capnp.IsStruct (JsonValue msg) where
    fromStruct struct = do
        tag <-  Codec.Capnp.getWordField struct 0 0 0
        case tag of
            6 -> JsonValue'call <$>  (Data.Capnp.Untyped.getPtr 0 struct >>= Codec.Capnp.fromPtr (Data.Capnp.Untyped.message struct))
            5 -> JsonValue'object <$>  (Data.Capnp.Untyped.getPtr 0 struct >>= Codec.Capnp.fromPtr (Data.Capnp.Untyped.message struct))
            4 -> JsonValue'array <$>  (Data.Capnp.Untyped.getPtr 0 struct >>= Codec.Capnp.fromPtr (Data.Capnp.Untyped.message struct))
            3 -> JsonValue'string <$>  (Data.Capnp.Untyped.getPtr 0 struct >>= Codec.Capnp.fromPtr (Data.Capnp.Untyped.message struct))
            2 -> JsonValue'number <$>  Codec.Capnp.getWordField struct 1 0 0
            1 -> JsonValue'boolean <$>  Codec.Capnp.getWordField struct 0 16 0
            0 -> pure JsonValue'null
            _ -> pure $ JsonValue'unknown' tag

instance Codec.Capnp.IsPtr (JsonValue msg) where
    fromPtr = Codec.Capnp.structPtr
instance Codec.Capnp.IsPtr (Data.Capnp.Untyped.ListOf (JsonValue msg)) where
    fromPtr = Codec.Capnp.structListPtr

newtype JsonValue'Call msg = JsonValue'Call Data.Capnp.Untyped.Struct

instance Codec.Capnp.IsStruct (JsonValue'Call msg) where
    fromStruct = pure . JsonValue'Call
instance Codec.Capnp.IsPtr (JsonValue'Call msg) where
    fromPtr = Codec.Capnp.structPtr
instance Data.Capnp.BuiltinTypes.Generic.ListElem msg (JsonValue'Call msg) where
    newtype List msg (JsonValue'Call msg) = List_JsonValue'Call (Data.Capnp.Untyped.ListOf Data.Capnp.Untyped.Struct)
    length (List_JsonValue'Call l) = Data.Capnp.Untyped.length l
    index i (List_JsonValue'Call l) = JsonValue'Call <$> Data.Capnp.Untyped.index i l
instance Data.Capnp.BuiltinTypes.Generic.MutListElem s (JsonValue'Call (Data.Capnp.Message.Mutable.Message s)) where
    setIndex (JsonValue'Call elt) i (List_JsonValue'Call l) = error "TODO: Generate code for setIndex"

instance Codec.Capnp.IsPtr (Data.Capnp.Untyped.ListOf (JsonValue'Call msg)) where
    fromPtr = Codec.Capnp.structListPtr
get_JsonValue'Call'function :: Data.Capnp.Untyped.ReadCtx m => JsonValue'Call msg -> m Data.Capnp.BuiltinTypes.Text
get_JsonValue'Call'function (JsonValue'Call struct) =
    Data.Capnp.Untyped.getPtr 0 struct
    >>= Codec.Capnp.fromPtr (Data.Capnp.Untyped.message struct)


has_JsonValue'Call'function :: Data.Capnp.Untyped.ReadCtx m => JsonValue'Call msg -> m Bool
has_JsonValue'Call'function(JsonValue'Call struct) = Data.Maybe.isJust <$> Data.Capnp.Untyped.getPtr 0 struct
get_JsonValue'Call'params :: Data.Capnp.Untyped.ReadCtx m => JsonValue'Call msg -> m (Data.Capnp.Untyped.ListOf (JsonValue msg))
get_JsonValue'Call'params (JsonValue'Call struct) =
    Data.Capnp.Untyped.getPtr 1 struct
    >>= Codec.Capnp.fromPtr (Data.Capnp.Untyped.message struct)


has_JsonValue'Call'params :: Data.Capnp.Untyped.ReadCtx m => JsonValue'Call msg -> m Bool
has_JsonValue'Call'params(JsonValue'Call struct) = Data.Maybe.isJust <$> Data.Capnp.Untyped.getPtr 1 struct
newtype JsonValue'Field msg = JsonValue'Field Data.Capnp.Untyped.Struct

instance Codec.Capnp.IsStruct (JsonValue'Field msg) where
    fromStruct = pure . JsonValue'Field
instance Codec.Capnp.IsPtr (JsonValue'Field msg) where
    fromPtr = Codec.Capnp.structPtr
instance Data.Capnp.BuiltinTypes.Generic.ListElem msg (JsonValue'Field msg) where
    newtype List msg (JsonValue'Field msg) = List_JsonValue'Field (Data.Capnp.Untyped.ListOf Data.Capnp.Untyped.Struct)
    length (List_JsonValue'Field l) = Data.Capnp.Untyped.length l
    index i (List_JsonValue'Field l) = JsonValue'Field <$> Data.Capnp.Untyped.index i l
instance Data.Capnp.BuiltinTypes.Generic.MutListElem s (JsonValue'Field (Data.Capnp.Message.Mutable.Message s)) where
    setIndex (JsonValue'Field elt) i (List_JsonValue'Field l) = error "TODO: Generate code for setIndex"

instance Codec.Capnp.IsPtr (Data.Capnp.Untyped.ListOf (JsonValue'Field msg)) where
    fromPtr = Codec.Capnp.structListPtr
get_JsonValue'Field'name :: Data.Capnp.Untyped.ReadCtx m => JsonValue'Field msg -> m Data.Capnp.BuiltinTypes.Text
get_JsonValue'Field'name (JsonValue'Field struct) =
    Data.Capnp.Untyped.getPtr 0 struct
    >>= Codec.Capnp.fromPtr (Data.Capnp.Untyped.message struct)


has_JsonValue'Field'name :: Data.Capnp.Untyped.ReadCtx m => JsonValue'Field msg -> m Bool
has_JsonValue'Field'name(JsonValue'Field struct) = Data.Maybe.isJust <$> Data.Capnp.Untyped.getPtr 0 struct
get_JsonValue'Field'value :: Data.Capnp.Untyped.ReadCtx m => JsonValue'Field msg -> m (JsonValue msg)
get_JsonValue'Field'value (JsonValue'Field struct) =
    Data.Capnp.Untyped.getPtr 1 struct
    >>= Codec.Capnp.fromPtr (Data.Capnp.Untyped.message struct)


has_JsonValue'Field'value :: Data.Capnp.Untyped.ReadCtx m => JsonValue'Field msg -> m Bool
has_JsonValue'Field'value(JsonValue'Field struct) = Data.Maybe.isJust <$> Data.Capnp.Untyped.getPtr 1 struct