{-# OPTIONS_GHC -Wno-unused-imports #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MultiParamTypeClasses #-}
module Capnp.ById.Xb8630836983feed7 where

-- Code generated by capnpc-haskell. DO NOT EDIT.
-- Generated from schema file: capnp/persistent.capnp

import Data.Int
import Data.Word
import qualified Data.Bits
import qualified Data.Maybe
import qualified Codec.Capnp
import qualified Data.Capnp.BuiltinTypes
import qualified Data.Capnp.TraversalLimit
import qualified Data.Capnp.Untyped

import qualified Capnp.ById.Xbdf87d7bb8304e81

newtype Persistent'SaveResults = Persistent'SaveResults Data.Capnp.Untyped.Struct

instance Codec.Capnp.IsStruct Persistent'SaveResults where
    fromStruct = pure . Persistent'SaveResults
instance Codec.Capnp.IsPtr Persistent'SaveResults where
    fromPtr = Codec.Capnp.structPtr

instance Codec.Capnp.IsPtr (Data.Capnp.Untyped.ListOf Persistent'SaveResults) where
    fromPtr = Codec.Capnp.structListPtr
get_Persistent'SaveResults'sturdyRef :: Data.Capnp.Untyped.ReadCtx m => Persistent'SaveResults -> m (Maybe Data.Capnp.Untyped.Ptr)
get_Persistent'SaveResults'sturdyRef (Persistent'SaveResults struct) =
    Data.Capnp.Untyped.getPtr 0 struct
    >>= Codec.Capnp.fromPtr (Data.Capnp.Untyped.message struct)


has_Persistent'SaveResults'sturdyRef :: Data.Capnp.Untyped.ReadCtx m => Persistent'SaveResults -> m Bool
has_Persistent'SaveResults'sturdyRef(Persistent'SaveResults struct) = Data.Maybe.isJust <$> Data.Capnp.Untyped.getPtr 0 struct
newtype Persistent'SaveParams = Persistent'SaveParams Data.Capnp.Untyped.Struct

instance Codec.Capnp.IsStruct Persistent'SaveParams where
    fromStruct = pure . Persistent'SaveParams
instance Codec.Capnp.IsPtr Persistent'SaveParams where
    fromPtr = Codec.Capnp.structPtr

instance Codec.Capnp.IsPtr (Data.Capnp.Untyped.ListOf Persistent'SaveParams) where
    fromPtr = Codec.Capnp.structListPtr
get_Persistent'SaveParams'sealFor :: Data.Capnp.Untyped.ReadCtx m => Persistent'SaveParams -> m (Maybe Data.Capnp.Untyped.Ptr)
get_Persistent'SaveParams'sealFor (Persistent'SaveParams struct) =
    Data.Capnp.Untyped.getPtr 0 struct
    >>= Codec.Capnp.fromPtr (Data.Capnp.Untyped.message struct)


has_Persistent'SaveParams'sealFor :: Data.Capnp.Untyped.ReadCtx m => Persistent'SaveParams -> m Bool
has_Persistent'SaveParams'sealFor(Persistent'SaveParams struct) = Data.Maybe.isJust <$> Data.Capnp.Untyped.getPtr 0 struct