{-# LANGUAGE DuplicateRecordFields #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# OPTIONS_GHC -Wno-unused-imports #-}
module Data.Capnp.ById.Xa184c7885cdaf2a1.Pure where

-- Code generated by capnpc-haskell. DO NOT EDIT.
-- Generated from schema file: schema/capnp/rpc-twoparty.capnp

import Data.Int
import Data.Word

import Data.Capnp.Untyped.Pure (List)
import Data.Capnp.BuiltinTypes.Pure (Data, Text)

import qualified Data.Capnp.Untyped.Pure
import qualified Data.Capnp.Untyped
import qualified Codec.Capnp

import qualified Data.Capnp.ById.Xbdf87d7bb8304e81.Pure
import qualified Data.Capnp.ById.Xbdf87d7bb8304e81

data JoinKeyPart
    = JoinKeyPart
        { joinId :: Word32
        , partCount :: Word16
        , partNum :: Word16
        }
    deriving(Show, Read, Eq)

instance Data.Capnp.Untyped.ReadCtx m b
    => Codec.Capnp.IsStruct m JoinKeyPart b
  where
    fromStruct = undefined

data JoinResult
    = JoinResult
        { joinId :: Word32
        , succeeded :: Bool
        , cap :: Maybe (Data.Capnp.Untyped.Pure.PtrType)
        }
    deriving(Show, Read, Eq)

instance Data.Capnp.Untyped.ReadCtx m b
    => Codec.Capnp.IsStruct m JoinResult b
  where
    fromStruct = undefined

data Side
    = Side'server
    | Side'client
    | Side'unknown' (Word16)
    deriving(Show, Read, Eq)

data ProvisionId
    = ProvisionId
        { joinId :: Word32
        }
    deriving(Show, Read, Eq)

instance Data.Capnp.Untyped.ReadCtx m b
    => Codec.Capnp.IsStruct m ProvisionId b
  where
    fromStruct = undefined

data VatId
    = VatId
        { side :: Side
        }
    deriving(Show, Read, Eq)

instance Data.Capnp.Untyped.ReadCtx m b
    => Codec.Capnp.IsStruct m VatId b
  where
    fromStruct = undefined

